spring.application.name=GymManagment

# Parametri di al Db MySQL
spring.datasource.driver.class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/gym_management
spring.datasource.username = root
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.default_schema=public

#Parametri di configurazione di Logback
logging.pattern.console = %-5level %logger{36} - %msg%n
logging.pattern.file = %d{dd-MM-YYYY HH:mm:ss.SSS} [%thread] %-5level %logger
logging.file.path = logs/
logging.file.name = application.log
logging.level.root = INFO

# Parametri di configurazione JWT
app.jwt-secret =secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
app.jwt-expiration-milliseconds= 86400000

# Attributi superAdmin
user.admin.username = AldoApache
user.admin.password = admin
user.admin.email = e.gorlomi@mail.com
